import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import StoreModal from '@/components/modals/StoreModal';
import ClientProvider from '@/components/ClientProvider';
import { Toaster } from 'react-hot-toast';
import { ThemeProvider } from '@/components/ThemeProvider';

export const metadata = {
  title: 'Ecommerce Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html
        lang="ko"
        className="antialiased scroll-smooth"
        suppressHydrationWarning
      >
        <body>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ClientProvider>
              <StoreModal />
              {children}
              <Toaster />
            </ClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
