import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import StoreModal from '@/components/modals/StoreModal';

export const metadata = {
  title: 'Ecommerce Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="ko">
        <body>
          <StoreModal />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
